# frozen_string_literal: true

source "https://rubygems.org"

gem 'pry', group: :development
gem 'pry-doc', group: :development
gem 'rubocop', group: :development
gem 'minitest', group: :development
gem 'rake', group: :development
# gem "rails"
